### ISSUE TITLE
Trained model not in repo

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [mehmetilker/spacy-tr#1]
Hi Mehmetilker!

I was so happy when I saw you've trained a Turkish model from the UD_Turkish-IMST treebank!
If the training was successful, can you please upload the trained model to your repo?

Best,
Barney

**Comment by mehmetilker** [comment]
Hi @BarnabasSzabolcs 

Since github does not accept big files,  I could not upload models.
I created this repo for spaCy v2 long time ago.

You can build a new model for V3 easily.
Let me know if you need help.

**Comment by BarnabasSzabolcs** [comment]
Thank you @mehmetiker for offering your help! 
I'll get back to you once I'll find the time to get down to making this spaCy training.

If someone else would stumble on this thread, it turns out, Stanza (a similar engine to spaCy) has support for Turkish language:
https://stanfordnlp.github.io/stanza/available_models.html
Its training set has POS info for 110.000+ distinct Turkish words. (see: Universal Dependencies)

Also, Stanza models can be used as if they were spaCy models, via https://github.com/explosion/spacy-stanza

So, the following program does the trick and now `nlp` works exactly as if it was called with spacy.load():
```
import stanza
import spacy_stanza

# Download the stanza model if necessary
stanza.download("tr")

# Initialize the pipeline
nlp = spacy_stanza.load_pipeline("tr")
```
